CFLAGS=-Wall -std=c99
CFLAGS+=-MMD -MP
LDFLAGS=-lm

-include pre.mk

SOURCEFILES=$(wildcard *.c)
EXES=$(patsubst %.c,%,$(filter-out $(IGNOREC),$(SOURCEFILES)))
TESTS=$(patsubst %,%.test,$(EXES))

all: $(EXES)

-include post.mk

test: $(TESTS)

inspect:
	@echo "source files: $(SOURCEFILES)"
	@echo "executable files: $(EXES)"
	@echo "test targets: $(TESTS)"

$(TESTS): %.test: %
	./$<
	@echo

.PHONY: all test inspect %.test clean print
clean:
	rm -f $(EXES) *.dat *.o *.d core

# Then the autogenerated rule files are included here - the '-' in front of
# include suppresses superfluous warnings about missing .d files
-include $(SOURCEFILES:.c=.d)

